// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtEioXiVu__BiPBsLLcgz08SyEbSYDrAk',
    appId: '1:200262724250:web:b0fb933a5f1df0aca9cd23',
    messagingSenderId: '200262724250',
    projectId: 'instagramc-642c8',
    authDomain: 'instagramc-642c8.firebaseapp.com',
    storageBucket: 'instagramc-642c8.appspot.com',
    measurementId: 'G-2K044EPM8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVXB8XPNMOnIDkt73Qprrn8A_8uI16U-I',
    appId: '1:200262724250:android:3706cf51b76e4a7fa9cd23',
    messagingSenderId: '200262724250',
    projectId: 'instagramc-642c8',
    storageBucket: 'instagramc-642c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7_Mw4tJV_FRmFqh7jh-uwaCr0R5WrMf8',
    appId: '1:200262724250:ios:4996e21ef78f3c38a9cd23',
    messagingSenderId: '200262724250',
    projectId: 'instagramc-642c8',
    storageBucket: 'instagramc-642c8.appspot.com',
    iosBundleId: 'com.example.instagramc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7_Mw4tJV_FRmFqh7jh-uwaCr0R5WrMf8',
    appId: '1:200262724250:ios:97fb9495f38457a5a9cd23',
    messagingSenderId: '200262724250',
    projectId: 'instagramc-642c8',
    storageBucket: 'instagramc-642c8.appspot.com',
    iosBundleId: 'com.example.instagramc.RunnerTests',
  );
}
